@startuml
class Restaurant{
String name
int restaurant_id
}

class Menu {
int restaurant_id
int menu_id
}

class Food {
int menu_id
int item_number
String name
}

class Order {
int oder_number
int item_number
}

class Customer {
int customer_id
int restaurant_id
int order_number
}

Restaurant "1" -- "1" Menu : > has
Menu "1" -- "*" Food : > contains
Customer "*" -- "*" Restaurant : > eats at
Customer "1" -- "1" Order : > orders
Order "*" -- "*" Food : > contains
@enduml