= Pflichtenheft Restaurant-Bestellsystem
:sectnums:

 Version: 1.0
 Version Date: 22.01.2023
 Autoren:
 -	Armin Salkovic
 -	Abdullah Al Desoky
 -	Balint Balazs
 -   Sukhbat Munkh

== Ausgangssituation
Wir sind ein Team aus 4 Schülern. Wir arbeiten in der HTBLA Leonding im Fach SYP an einem Projekt.

== Ist-Zustand
Momentan werden wie üblich Kellner in Restaurants eingesetzt, um Kunden zu bedienen
und um die gewünschte Bestellung aufzunehmen.

== Problemstellung
Zurzeit gibt es immer mehr Missverständnisse zwischen Kellnern und Kunden in Bezug auf das Nichtsprechen
der selben Sprache oder normale Verständnisprobleme.

== Aufgabenstellung
=== Funktionale Anforderungen

* Produktkatalog
** Die Anwendung muss einen Produktkatalog bereitstellen, in dem Kunden das Angebot des Restaurants einsehen und auswählen können.

* Bestellung aufgeben
** Die Anwendung muss es Kunden ermöglichen, Bestellungen aufzugeben und die ausgewählten Produkte zu bestellen.

==== Use-Case-Diagram

[plantuml]
----
include::./plantuml/ucd.puml[]
----

Das Entwickeln einer Anwendung, die es Restaurants ermöglicht, Bestellungen von Kunden aufzunehmen, indem eine intuitive
Benutzeroberfläche bereitgestellt wird.

=== Nicht-funktionale Anforderungen

* Performance
** Die Anwendung muss in der Lage sein, schnell auf Kundenanfragen zu reagieren und Bestellungen in Echtzeit aufzunehmen.

* Verfügbarkeit
** Die Anwendung muss so lange der Restaurant offen hat verfügbar sein, um Kundenbestellungen entgegenzunehmen.

* Benutzerfreundlichkeit
** Die Anwendung muss eine intuitive Benutzeroberfläche bereitstellen, die es Kunden ermöglicht, einfach und schnell Bestellungen aufzugeben.

== Ziele
* Bessere Übersicht über das Menü
* Reduzierung der Zeit für Aufnahme von Bestellungen
* Steigerung der Genauigkeit bei der Erfassung von Bestellungen
* Schnellere/einfachere Entscheidungsfindung
* Schnellerer Ablauf bei der Bestellung
* Keine Missverständnisse zwischen dem Kunden und dem Personal

== Mengengerüst
* Die Anwendung wird auf einer webbasierten Plattform entwickelt
* Die Anwendung ist nur für Restaurants zugänglich

== Rahmenbedingungen
* Das Projekt muss innerhalb eines definierten Zeitrahmens und Budgets umgesetzt werden
* Die Anwendung muss den geltenden Datenschutzgesetzen entsprechen
* Programmiersprache: Java

== Datenmodell

[plantuml]
----
include::./plantuml/dom.puml[]
----

== GUI

Skizzen einfügen!

== Lieferumfang
Der Kunde erhält eine benutzerfreundliche Anwendung, über die er Bestellungen aufgeben kann. +
Die Anwendung ermöglicht es ihm, die Speisekarten und Menüs des Restaurants einzusehen und seine Bestellungen einfach und schnell aufzugeben. +
Er erhält auch eine Bestätigung über erfolgreich aufgegebene Bestellungen.

== Abnahmekriterien
* Die Anwendung erfüllt alle festgelegten funktionellen Anforderungen
* Die Dokumentation der Anwendung ist vollständig und verständlich
* Die Anwendung ist stabil und fehlerfrei
* Die Anwendung ist benutzerfreundlich und intuitiv zu bedienen
* Die Anwendung hat erfolgreich die vereinbarten Tests bestanden
* Der Kunde bestätigt, dass die Anwendung seinen Erwartungen entspricht
