@startuml
left to right direction

actor "Customer" as c
actor "Service" as s

rectangle PickYourOrder {
usecase "order food" as o
usecase "receive order" as r
usecase "view on order" as v
usecase "pay" as p
}

c -- p
c -- o
s -- r


r .> v : include
@enduml