@startuml
class Dish {
dishNr: int
name: String
}

class Product {
dishNr: int
itemNr: int
name: String
price: double
}

class Bill {
billNr: int
workingNr: int
tableNr: int
}

class Service {
workingNr: int
name: String
}

class Table {
workingNr: int
tableNr: int
}

class Order {
orderNr: int
billNr: int
itemNr: int
amountOfItem: int
price: double
}


Service "1" -- "*" Bill : > collects
Bill "*" -- "1" Table : < consumes
Service "1" -- "*" Table : > serves
Dish "1" -- "*" Product : > contains
Bill "*" -- "*" Product : > contains
(Bill, Product) . Order
@enduml