@startuml
left to right direction
actor "Customer" as fc
rectangle Restaurant {
usecase "order food" as UC1
usecase "eat food" as UC2
usecase "pay for order" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3
@enduml